bug: [빵집등록] ios 사진 업로드 시 등록 불가 이슈
endbreadkings/breadgood pull request #10
Opened 2022-01-03 17:12 UTC by kyeonghyeon

### 요약
빵집 등록 시 ios 에서 이미지 업로드하면 이미지 업로드가 되지 않음

### 작업내역
빵집 등록 시 ios 에서 이미지 업로드하면 'heic' 확장자이므로 업로드가 되지 않아 'jpeg'으로 변환 후 업로드하도록 함.

### 작성자의 고민
발생할 수 있는 모든 확장자 경우를 포함해야하는 것이 아닌가 고민하고 있습니다 따라서 refactoring 이 필요할지 고민하고 있습니다.

2022-01-05 03:32 UTC, doyoung0205 requested changes
72번 브랜치에 PR 내용과 겹치는 부분이 있네요. 
피드백은 해당 브랜치 PR 에 남겼습니다.
이대로 머지가 되면 충돌이 발생할 수 도 있을 것 같습니다.

2022-01-05 03:34 UTC, doyoung0205 commented
발생할 수 있는 모든 확장자 경우를 포함해야하는 것이 아닌가 고민하고 있습니다 따라서 refactoring 이 필요할지 고민하고 있습니다.

> 사용자가 핸드폰에서 업로드 할 경우에 어떤 확장자가 있는지 알아볼 필요가 있을 것 같습니다. 서버에서는 JPEG, JPG, PNG 같은 HTML 보여질 수 있는 확장자만 받도록 강제한 뒤 다른 확장자가 왔을 경우 해당 확장자를 변환을 고려해도 괜찮을 것 같습니다.

2022-01-05 14:17 UTC, kyeonghyeon commented
@doyoung0205 피드백 감사합니다. 직접 핸드폰으로 찍은 사진을 업로드한다고 가정했을 때, JPEG, JPG, PNG 같은 일반적으로 많이 사용되는 이미지 확장자 외에 사용되는 확장자로 HEIC 만 있는 걸로 알고 있습니다. 
저희가 휴대폰으로 찍지 않은 사진도 받아들일 건지를 결정해야할 것 같습니다. 이럴 경우 svg나 pdf 까지도 포함이 될 수 있는데, 이럴 경우 1. 현재 사용하고 있는 패키지가 아니라 다른 패키지를 이용하여 이미지를 선택할 수 있도록 해야하고 2. 변환할 방법도 생각해봐야할 것 같습니다.
저는 일단 HEIC, JPEG, JPG, PNG 만 업로드 된다고 가정해도 될 것 같은데, 혹시 두 분 의견은 어떠신가요? @doyoung0205  @younger-k

2022-01-05 14:52 UTC, kyeonghyeon commented
@doyoung0205 @younger-k 피드백 주신 것처럼 당장은 .raw 나 .pdf  등 특수 경우에 대한 처리는 하지 않겠습니다. 도영님께서 확인해주신 바로는 .svg, .gif, .heic, jpec, .jpg, .png, .webP 확장자가 서버에서 허용되며, .heic 를 제외한 상기 확장자들은 프론트단에서 별도의 확장자 변환이 필요 없음을 확인했습니다. 따라서 .heic에 대해서만 별도 확장자 변환 작업 코드 작성한 것으로(본 커밋) 이슈 resolve 하겠습니다.

2022-01-05 15:13 UTC, doyoung0205 commented
.svg, .gif, .heic, jpec, .jpg, .png, .webP 확장자가 서버에서 허용 되도록 코드를 수정하였습니다.
괜찮으시다면 리뷰 부탁드립니다.

2022-01-05 15:18 UTC, kyeonghyeon commented on breadgood-server/src/main/java/com/bside/breadgood/util/FileUtils.java
> +    private static final Set<String> AVAILABLE_EXTENSION_GROUP = Set.of("JPG", "JPEG", "PNG", "WEBP", "SVG");
도영님 혹시 gif 파일은 허용하지 않는건가요?

2022-01-05 15:25 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/util/FileUtils.java
> +    private static final Set<String> AVAILABLE_EXTENSION_GROUP = Set.of("JPG", "JPEG", "PNG", "WEBP", "SVG");
깜빡했네요 해당 부분 재커밋 했어요 !

2022-01-05 15:52 UTC, kyeonghyeon reviewed
GIF 확장자 추가 확인했습니다.

2022-01-05 16:09 UTC, kyeonghyeon commented
피드백 반영하여(72번 브랜치에 남겨주신) 커밋 다시 올렸습니다. 리뷰 부탁드립니다. @doyoung0205 @younger-k

2022-01-06 08:15 UTC, doyoung0205 requested changes
경현님 고생하셨습니다.
고민할 만한 내용 피드백으로 남겼습니다.
경현님의 생각 말씀주시면 감사하겠습니다.

2022-01-06 08:15 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
이전에 리뷰 드렸던 부분이 주석 처리가 되었네요. 
주석처리가 되어도 괜찮나요? 
괜찮다면 주석은 최대한 삭제 하는 것이 좋을 것 같아요.

2022-01-06 08:15 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>        print(i);
하는일이 많아 보이네요. 
1. for 문
2. 파일 경로 구하기
3. 확장자를 구하기
4. HEIC 확장자일 경우 변환

메소드 나 함수로 나눠보는 것을 권장드립니다.

추가로 서버에서도 "JPG", "PNG" .. 등의 유효성 검사를 하고 있지만 flutter 진영에서도 검사를 할 수 있으면 좋을 것 같습니다.
그렇다면 확장자 검사에 대해서 API 를 호출 비용을 아낄 수 있지 않을까요?

2022-01-06 08:20 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
저번에 코멘트에 남겼듯이 path package import 할 시 관습적으로 p 로 쓰는 것으로 알고있습니다. 그런데 p 보다는 의미를 알 수 있도록 단어로 작성하는 것을 추천하셔서 path 로 작성하는 것을 고려하였으나, path 는 실제 코드에서 변수로 자주 사용하고 있습니다. 그래서 대문자로 사용하였습니다.

2022-01-06 08:21 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
어제 빵굽 시간에 말씀드렸던 것처럼 이 부분은 http response 를 받아 code 확인 후 오류처리를 추가해줘야할 부분으로 생각됩니다. 따라서 reponse status 확인하는 디버깅 코드를 임시로 남겼습니다.

2022-01-06 08:21 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
제가 생각하기에는 대문자로만 이루어져있는 변수는 상수로 알고 있는데, 네이밍컨벤션에 괜찮을까요?
코딩 컨벤션이 카멜케이스라면 Path 라던지 PathUtils 같은건 어떤가요?

2022-01-06 08:26 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
깔끔한 코드를 관리하기 위해서는 현재 사용하지 않는 코드는 주석 보다는 삭제를 해야 하는 것이 맞다고 생각합니다.
디버깅을 위한 주석이라면 디버깅 툴을 이용해보는건 어떤가요?

2022-01-06 08:26 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
>        print(i);
1 은 공통적으로 들어가는 부분이니 제하고
2와 3,4 두 부분으로 나누어 다시 변경하도록 하겠습니다
제 기준에서는 아주 길거나 복잡하지 않고 재사용성도 없어보여 코드가 더 복잡해질까 나누지 않았습니다

또 제안하신 것처럼 백엔드에서 설정한 확장자 리스트들만 받는 것으로 하겠습니다. 다만 이럴 경우 해당 확장자가 아닐 때 어떻게 할 지 정의가 되어야 구현부를 작성할 수 있을 것으로 보입니다.

2022-01-06 08:28 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
플러터에서 해당 패키지는 보통 문자 'p' 를 이용하여 import 하고 있는데, 도영님께서 추천해주신 변수도 좋지만 관습적인 것을 따르는 것은 어떨까 고민하고 있습니다

2022-01-06 08:31 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>        print(i);
이런식으로 메소드 분리를 하면 좀더 읽기 쉬운 코드가 되지 않을 까 싶습니다.
컨셉이니 참고만 해주세요.
```
    for (int i = 0; i < imageList.length; i++) {
      String path = getFilePath(imageList[i].identifier);
      String fileExtension = getExtension(path);
      validateFileExtension(fileExtension);
      print(i);
      fileList.add(File(path));
    }
```

2022-01-06 08:31 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
해당 피쳐가 미완 상태라 추후 해당 부분 보완할 때 다시 추가해야할 부분이라면 해당 부분 작업 시마다 추가 작업하는 것보다는 남겨두고 완료 시 리팩토링 하는 것이 좋다고 생각하고 있습니다. 관리상 문제가 된다면 삭제하도록 하겠습니다.

2022-01-06 08:35 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
관습을 따라가는 것도 좋지만 컨벤션이 있다면 컨벤션을 지키는 것이 더 중요하다고 생각합니다.
해당 링크 보시고 결정은 경현님이 내려주세요.
https://dart.dev/tools/linter-rules#library_prefixes

2022-01-06 08:36 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
>        print(i);
위에 저도 2 부분과 3+4 기능으로 나누는 것으로 말씀드렸습니다. 같은 맥락인 것 같습니다! 다만 말씀하신것처럼 백엔드에서와 같이 확장자를 걸러야한다면 validateExtension 시 return 값으로 error 여부를 반환해야할 것 같고, 현재는 오류 처리 부분이 계획되지 않았으므로 error 반환되어도 처리하는 구현부는 추가하지 않을 생각입니다.

2022-01-06 08:36 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
사용하지 않는 코드가 계속 주석 처리로 남아있다면 가독성이나 다른 개발자들에게 혼란이 올 수 있다고 생각합니다.
이 부분도 경현님이 고민해보시고 결정된 부분와 이유와 함께공유 해주시면 감사하겠습니다.

2022-01-06 08:40 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
아래 링크 확인하시면 실제 flutter dev 에서 해당 패키지를 사용할 때 import 를 "p" 로 하고 있고(제가 처음에 작성했던 커밋)
[https://pub.dev/packages/path](https://pub.dev/packages/path)
도영님께서 참고로 공유해주신 부분은 package naming을 camel case 가 아닌 snake case  따르는 것이 좋다는 내용으로 이해했는데 혹시 제가 잘못 이해했을까요?

2022-01-06 08:43 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
>    // final responseJson = jsonDecode(utf8.decode(responseStream.bodyBytes));
추후 사용해야할 것 같은 코드를 남겨둔 부분에 대해서는 주석처리 시 이유를 함께 남겨두도록 하겠습니다. 이 외에 추후 사용 계획이 없지만 단순 디버깅을 위해 남겨두었던 코드는 삭제하도록 하겠습니다. 위 내용은 비단 본 커밋에만 해당되는 것이 아니므로 일괄 적용하는 커밋 작성하여 "refactor: [공통]" 으로 적용하도록 하겠습니다. 추후 공유드릴게요!

2022-01-06 09:10 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
네 맞습니다. `dart` 문법의 `import` 에 관한 컨벤션 이기도 하죠.
경현님이 보내주신 링크로는 `p` 를 관습이라고 생각하기엔 애매한 부분이 있는 것 같습니다.
단지 `p` 라는 `prefix` 를 이용하는 사용방법 중 하나라는 가이드로 보입니다.

2022-01-06 09:20 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
저는 flutter dev 의 package usage 설명을 참고하여

아래와 같이 http package 는 http 라는 prefix 로 package import 하는 예가 나와있고,
[https://pub.dev/packages/http](https://pub.dev/packages/http)

아래와 같이 path package 는 path 의 p 를 따와서 package import 시 prefix 로 사용한다고 이해했고,
[https://pub.dev/packages/path](https://pub.dev/packages/path)

제가 확인한 모든 stack overflow 이슈들에서도 flutter dev 의 가이드를 따른 것인지 p 라는 prefix 를 사용하여 해당 package  를 import 하는 것으로 확인했고,

따라서 다른 flutter 개발자분들이 보기에 해당 가이드를 따르는 것이 좋을 것으로 이해했습니다. 

하지만 다른 개발자의 이해가 저해되는 부분이라면 path 로 prefix 변경하도록 하겠습니다! 피드백 감사합니다 ~~!

2022-01-06 09:29 UTC, kyeonghyeon commented
꼼꼼하게 피드백 주셔서 감사해용 여러분 @doyoung0205 @doyoung0205 
피드백 내용대로 아래 세 가지 내용 적용 후 다시 리뷰 요청드리도록 하겠습니드
1. Path library prefix 를 path 로 변경( 코드 내에서 사용 중이던 변수 path 의 이름을 변경할 예정 )
2. TBC 인 코드 부분은 주석 처리하는 이유도 함께 남기고, 단순 디버깅 코드 삭제 -> 전체적으로 적용될 부분으로 본 브랜치와 이슈 성격 다르기 때문에 다른 브랜치에서 작업 후 공유드리겠습니다
3. 이미지 업로드 시 패스 추출부분과 이미지 변환 부분 분리 및 이미지 변환 부분에 확장자 validate 하는 코드 추가

2022-01-06 09:39 UTC, doyoung0205 commented
저도 코드 퀄리티가 좋지 않은걸요... 
제가 드린 피드백은 지금도 너무 좋지만 더 좋아질 수 있는 생각이 나서 피드백으로 드린 것 뿐이니 
마음에 많이 담아두지 않으셔도 좋을 것 같습니다. 👍🏻 

또한 각자의 팀원이 읽기 쉬운 코드로 변화하는 과정이라 생각을 하고 있습니다.

아까 package 관련해서 많은 이슈가 있었는데, 
저는 pub.dev 에 있는 모든 패키지 가이드문서가 컨벤션을 지키지 않을 수 도 있다고 생각합니다.
대부분의 개발자가 해당 패키지 가이드를 따라갈 수도 있지만 저희는 ​공식적인 컨벤션 문서나 저희의 컨벤션을 따라가야 한다고 생각합니다. 🙇🏻

2022-01-06 15:28 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as PATH;
Dart official style documentation 참고하여 refactoring 한 번 하는 작업 갖도록 하겠습니다! (다른 브랜치로 열겠습니다!)

2022-01-06 15:47 UTC, kyeonghyeon commented
위 논의 후로 official 한 coding rule 에 대해서 공유해주신 후로 뭘 참고해야할까를 찾아보고 있는데요!
여기 코딩룰을 참고하려고 합니다.
https://api.flutter.dev/index.html

그런데 여기서도 path package 를 'p' 로 불러오고 있더라구요!
사실 말씀해주신 것처럼 이해를 돕기 위해 'p' 대신 'path' 로 prefix 바꾸려고 했는데 ,
자주 함께 쓰이는 File 구조체의 멤버에도 path 가 있어서 혼동이 예상되어 다른 옵션을 생각해야할 것 같습니다.
그래도 'p' 라는 prefix 보다는 'path_libary' 와 같이 우리만의 이름으로 쓰는게 나은 옵션일까요?

일반적으로 웹/앱 개발시 어떤 표준을 따르고, 또 어떻게 개발 기준을 만들어 나가는지 모르겠어서 여러분 생각 여쭙니다. @doyoung0205  @younger-k  
저는 공식적으로 release된 표준 문서 > 해당 언어를 사용하는 사람들의 conventional rule  > 함께 개발하는 사람들끼리의 약속 순으로 중요도를 생각해왔는데 혹시 어떻게 생각하시는지 궁금하네욥!! : )

2022-01-06 16:17 UTC, doyoung0205 commented
공식적인 release 문서는 https://dart.dev/tools/linter-rules 라고 생각합니다.
그리고 저는 함께 개발하는 사람들끼리의 약속 이 가장 중요하다고 생각합니다.

2022-01-06 18:15 UTC, kyeonghyeon commented
피드백 내용 정리하여 아래 변경 적용하였습니다. 리뷰 부탁드려요! @doyoung0205  @younger-k 
1. Path library prefix 를 path_lib 로 변경
3. 이미지 업로드 시 패스 추출부분과 이미지 변환 부분 분리 및 이미지 변환 부분에 확장자 validate 하는 코드 추가

2022-01-07 05:00 UTC, doyoung0205 requested changes
경현님 고민해볼만한 코멘트 남겨드려요.
한번 확인해보시고 반영해주시면 좋을 것 같아요.

2022-01-07 05:00 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    }
이 부분도 else if 가 꼭 필요한지 고민해보면 좋을 것 같아요.

2022-01-07 05:01 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +import 'package:path/path.dart' as path_lib;
피드백 잘 반영해주셨네요. 👍🏻

2022-01-07 05:02 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    List<String> allowedExtension = ["JPG", "JPEG", "PNG", "WEBP", "SVG", "GIF"];
allowedExtension 이 for 문을 돌 때마다 생성이 되는데, 전역으로 관리해도 괜찮을 것 같습니다.

2022-01-09 08:28 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    }
확장자 확인하고 나서 HEIC 확장자를 가진 파일일 시에 임시 path 를 설정(이미지 index 를 받아서) 하는 부분입니다.
말씀하신 것처럼 해당 부분과 묶으려면 파일 확장자를 확인하지 않고 일단 모든 이미지에 대해 변환된 패스를 저장해야하는 것 같은데.. 제가 잘못이해했을까요?

2022-01-09 08:29 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    List<String> allowedExtension = ["JPG", "JPEG", "PNG", "WEBP", "SVG", "GIF"];
좋은 지적인 것 같습니다! 변경적용하겠습니다

2022-01-09 08:30 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    else {
짧은 코드보다 이해하기 쉬운 코드를 위해 그랬던 것인데, 오히려 클린하지 않은 거로 보이는군요 간략하게 작성하도록 하겠습니다

2022-01-09 08:49 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    }
다른 방법을 찾아서 해볼게용~

2022-01-09 09:45 UTC, kyeonghyeon commented
아래 사항에 대해 리뷰 요청드립니다. @doyoung0205  @younger-k 
1. 불필요한 조건문 제거
2. 함수 별로 하나의 역할만 하도록 변경(Heic to Jpg path conversion 함수와 파일 확장자 verification 함수로 나누어 구현)
3. 불필요한 변수 생성 피하기 위한 지역변수의 전역변수화(allowedExtensions)
4. 불명확한 변수명 변경(allowedExtension => allowedExtensions)

2022-01-09 10:02 UTC, doyoung0205 requested changes
경현님 피드백 잘 반영해주셨습니다 ! 
고민해보면 좋을 만한 내용 다시 피드백 남겨드려요 ! 
확인해보시고 말씀주세요 !

2022-01-09 10:02 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    return File(jpgPath);
file 객체에서 HEIC path 를 꺼네서 jpg path 로 변경하고 File 객체를 생성하네요. 
해당 함수의 역할을 heic path 를 받아와서 jpg path 로 변경하는 거에 집중하는 함수로 만들어보는 것은 어떨까요?

2022-01-09 10:02 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +          path_lib.extension(imageFile.path).replaceAll('.', '');
이 부분도 가능하면 함수로 변경해보면 좋을 것 같아요 !

2022-01-09 10:03 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +        (await getTemporaryDirectory()).path + '/$fileIndex.JPG';
file index 가 없으면 임시로 변환된 파일을 저장할 path 를 만들어줄 때 unique 한 path 를 만들어줄 방법이 생각나지 않습니다. unique 하게 이름을 지정해주지 않으면 heic 파일을 여러개 올리려고 했을 시, 모두 같은 이름으로 저장되어 마지막에 선택한 heic 이미지가 여러개 올라가게 됩니다

2022-01-09 10:05 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    return File(jpgPath);
처음엔 그렇게 만들었는데 어떤 이유인지 모르겠으나 어떨 때는 이미지가 잘 올라가는데 어떨때는 마지막에 선택한 이미지가 여러개 올라가더라구요.. 더 알아보고 다시 변경 후 올려보겠습니다

2022-01-09 10:08 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +          path_lib.extension(imageFile.path).replaceAll('.', '');
fileExtension 을 추출하는 한 줄짜리 코드를 함수로 변경하는 것이 좋은가요? 혹시 이유를 여쭤봐도 될까요?

2022-01-09 10:21 UTC, kyeonghyeon commented
아래 부분 피드백 반영하였습니다. @doyoung0205 @younger-k 
1. 파일 확장자 추출 부분 함수화
2. heic to jpg 변환 함수에서 file 생성하는 부분 분리

2022-01-09 11:56 UTC, doyoung0205 requested changes
경현님 피드백 남겨드렸습니다. 
확인한번 해주세요 !

2022-01-09 11:56 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +      String fileExtension = ExtractFileExtension(imageFile);
메서드가 대문자로 시작해도 괜찮은가요?

2022-01-09 11:56 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +        String jpgPath = await ConvertHeicToJpg(imageFile, i);
이 부분도 대문자인데 괜찮을까요?

2022-01-09 11:56 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +        imageFile = File(jpgPath);
path 를 file 로 변환하는 부분이 분산되어 있네요. 
분산된 부분이 개선되면 좋을 것 같아요.

2022-01-09 11:56 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +        String jpgPath = await ConvertHeicToJpg(imageFile, i);
path 를 구하는 부분이 분산되어 있는 것 같아요. 
함수로 묶어주면 좋을 것 같습니다.

2022-01-09 11:56 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
>          (await getTemporaryDirectory()).path + '/$fileIndex.JPG';
이 부분 꼭 fileIndex 가 필요한지 좀 더 고민하면 좋을 것 같아요.
file name 이 되어도 괜찮을 것 같습니다.

2022-01-09 15:29 UTC, kyeonghyeon commented
리뷰 부탁드립니다 @doyoung0205  @younger-k 
함수명, parameter 구성, 함수 역할에 따른 분리등 위에서 @doyoung0205 님 피드백주신 부분 반영하였습니다.

2022-01-09 15:42 UTC, doyoung0205 requested changes
경현님 피드백 반영하느라 고생 많으셨습니다.
`validateFileExtension` 의 매개변수 네이밍만 수정되면 좋을 것 같습니다 !
끝까지 화이팅 입니다 !

2022-01-09 15:42 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +  bool validateFileExtension(String uri) {
path 를 매개변수로 넣는 것 같은데 매개변수가 uri 로 네이밍이 되어있네요

2022-01-09 15:42 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    return await HeicToJpg.convert(heicPath, jpgPath: convertedPath);
크으 깔끔하네요 !

2022-01-09 15:42 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +      path = await convertHeicToJpg(path);
변수에 할당 보다는 바로 return 하는 것이 좀더 좋지 않을까요?

2022-01-09 15:42 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    return false;
이 부분은 나중에 파일 확장자를 다루는 Enum 으로 관리되면 좋을 것 같습니다 !

2022-01-09 15:42 UTC, doyoung0205 commented on breadgood_app/lib/modules/register_review/register_review.dart
> +      fileList.add(File(imagePath));
되게 깔끔해졌네요 !

2022-01-09 15:48 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +  bool validateFileExtension(String uri) {
확인감사합니다

2022-01-09 15:49 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +      path = await convertHeicToJpg(path);
그렇게 변경하도록 하겠습니다

2022-01-09 15:50 UTC, kyeonghyeon commented on breadgood_app/lib/modules/register_review/register_review.dart
> +    return false;
파일 다루는 함수 및 클래스 관련하여 확장성에 대한 필요가 생기면 함께 정리하도록 하겠습니다

2022-01-09 15:52 UTC, kyeonghyeon commented
@doyoung0205 @younger-k 리뷰 요청드립니다
위에 피드백 주신 함수 flow 관련 개선하였고, uri로 잘못 쓰여진 함수 parameter 명 path로 변경하였습니다.

2022-01-09 16:01 UTC, doyoung0205 approved these changes
경현님 피드백 잘 반영해주셨네요.   
오랜기간동안 피드백 주고 받은 부분이 고생하게 했다는 죄송한 마음이 있으면서도 
시간이 없어서 맞춰주신건 아닌지 걱정도 되네요.

코드리뷰를 하는 문화를 겪게 된지 얼마 되지 않아서 저의 설명이 부족한 부분이 있지만 
계속해서 서로 좋은 코드라고 생각하는 부분이 있다면 이야기하면서 맞춰나아가 봐요 !
🙇🏻🙇🏻

2022-01-09 16:02 UTC, kyeonghyeon commented
귀찮을 수 있는 부분인데 서로 맞춰가기 위해 시간과 노력 할애해서 피드백 주신 것 알고 있습니다! 감사합니다! 코드리뷰를 하면서 제가 틀린 부분이든, 서로 다른 부분이든 알게 된다는 것 자체가 좋은 것 같습니다.

2022-01-09 16:14 UTC, merged