bug: [회원가입] 약관동의, 닉네임, 최애빵스타일 등록 시 화면 size 작아지는 이슈
endbreadkings/breadgood pull request #16
Opened 2022-02-05 08:09 UTC by kyeonghyeon

### 요약
회원 가입 과정에서 1.약관동의, 2. 닉네임 입력, 3. 최애빵스타일 선택의 화면 size 작아지는 이슈
### 작업내역
"SafeArea" 라는 widget 이 적용되어있어서 명시하지 않은 padding 이 추가되는 것이 문제였음.
모든 화면에 전체적으로 "SafeArea" 라는 Widget 이 적용되어있지는 않으므로, 여기에서도 삭제함.
### 작성자의 고민
"SafeArea" 라는 Widget 은 기기 별로 서로 다른 StatusBar 영역 등 차이에 영향 받지 않는 디자인을 할 수 있도록 도와주는 Widget 으로,
해당 Widget 적용된 상태에서 디자인을 가미한다면 기기별 차이를 고려하지 않아도 문제 없는 디자인을 할 수 있다고하는데,
해당 Widget 을 사용하면 디자이너의 의도와 다르게 화면 사이즈가 작아지고, 의도치않은 padding 으로 위아래에 검은 영역이 생겨버림.
하지만 기기별로 테스트해보지 않아도 디자인상 문제가 없을것이라는 장점이 있어서 두 가지 trade off 중에 고민함.
디자이너의 의도가 더 중요하다고 생각하여 해당 widget 을 삭제하는 것으로 결정함.

2022-02-05 13:47 UTC, doyoung0205 requested changes
PR 요청을 잘 해주셔서 이해가 잘되었습니다. 🥇  

경현님의 고민이랑 비슷한 부분일 수도 있는데, 
`SafeArea` 를 제거 했을 때 아래에 있는 이미지 처럼 기존에 있던 content 들의 위치가 모두 움직이진 않았는지 걱정되네요..


<details>
<summary>#### 예상 오류 케이스</summary>
<div markdown="1">       

![image](https://user-images.githubusercontent.com/39691109/152644418-0302e19f-ab0e-4ecf-91ab-963f8616f75a.png)

</div>
</details>



- 단순히 색상만 검은색에서 흰색으로 바꾼다거나 
- 페이지 마다 아래의 있는 옵션을 활용해서 조절

하는 방법은 어려운 부분인지 궁금합니다.

<details>
<summary>SafeArea 옵션</summary>
<div markdown="2">       

![image](https://user-images.githubusercontent.com/39691109/152644542-780d33e8-aeaf-41c8-9a33-b3942d254a99.png)

</div>
</details>

2022-02-05 13:47 UTC, doyoung0205 commented on breadgood_app/lib/modules/signup/screens/bread_style.dart
> +      child: Container(
잘못된 indent 를 👁️_👁️ 발견하였습니다.

2022-02-13 05:21 UTC, kyeonghyeon commented
현재까지 확인해본 결과 safearea 는 전체 적용하지 않고 이 부분해서도 제거하는 것으로 하겠습니다
Safearea widget 은 앱 화면에서 top 이나 bottom 에 display 하고 싶은 정보가 있을 때 필요한데
저희 디자인 상 그런 케이스가 없고, 특히 top 의 경우 appbar 를 사용하기 때문에 더욱이 정보를 display 할 일이 없습니다
Scaffold widget 을 사용하면서 safearea 를 사용하면 디자인 해주신 것과 다르게 status bar 가 검은 화면으로 나옵니다
굳이 safearea 를 사용하면서 top 부분만 부분적으로 적용되지 않게 하는 방법도 있겠으나 
빵긋 앱에서 safearea 를 사용해야 할 이유가 없는 것으로 판단되어 본 커밋 내용인 삭제하는 방향으로 결정했습니다

2022-02-13 13:42 UTC, kyeonghyeon commented
code indentation 수정하였고,
safeArea 는 말씀드린 위의 이유로 적용하지 않기로 결정하였습니다.
리뷰 부탁드립니다! @doyoung0205 @haedoang @younger-k

2022-02-13 15:33 UTC, doyoung0205 commented
@kyeonghyeon  님 고생하셨습니다 ! 좋은 결정인 것 같습니다.
제가 괜히 혼란을 드린건 아닌지 걱정이네요 ! ㅠㅠ 
도움이 필요하신 부분이있으시면 꼭 말씀주세요 !

2022-02-14 15:33 UTC, haedoang approved these changes
고생 많으셨습니다 😄 👍 💯 💯 
회의 때 잘 설명해주셔서 이해가 잘 되었어요~ 

사용하지 않는 import 제거와 문서 정렬(코드 포맷)을 하면 코드가 더 보기 깔끔해 질 것 같아요 

### shortcut
1) 사용하지 않는 import 제거
   -  안드로이드스튜디오: ⌃(control) + ⌥(option) + o
   - VSCode:                 ⇧(shift) + ⌥(option) + o
2) 문서 정렬(코드 포맷)
   - 안드로이드 스튜디오 :  ⌥(option) + ⌘(command) + l(Lowercase :L)
   - VSCode:                  ⇧(shift) + ⌥(option) + f

2022-02-16 14:27 UTC, merged