[빵집리스트] 빵집 리스트 최신순 정렬
endbreadkings/breadgood pull request #19
Opened 2022-02-06 15:24 UTC by younger-k

### 요약
빵집 리스트 정렬 기능

### 작업내역
현재는 최신순 정렬만 사용하지만, 이후에 정렬 기능 확장을 위하여 빵집 정렬 타입 Enum 추가하였습니다.
요청받은 Enum 타입에 따라 Stream을 정렬합니다.

### 작성자의 고민
정렬 타입이 추가될수록 `orderBySortType`의 if문이 늘어나게 되는데,,,, 어쩔 수 없는걸까요.. 더 좋은 방법 없을까요..?!

2022-02-06 17:02 UTC, doyoung0205 requested changes
연하님 고생하셨습니다.
이번 R&R 을 통해서 테스트 코드를 작성하기로 한 부분이 있어서 
테스트 코드가 작성이 가능하시다면 해주시면 좋을 것 같아요 !

아 그리고 저번에 public 한 기본생성자가 없을 때 나오는 이슈는 어떻게 되었나요? 잘 해결 하셨나용?

2022-02-06 17:02 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/dto/BakerySearchRequestDto.java
> +    public BakerySearchRequestDto(String city, String district, Set<Long> bakeryCategories, BakerySortType bakerySortType) {
다른 파라미터는 빈문자열이나 Null 이 허용 되는데, 
`BakerySortType` 으로 지정되면  "" 같은 빈문자열이 넘어올때 오류가 발생할 것 같아요.

2022-02-08 13:10 UTC, younger-k commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/dto/BakerySearchRequestDto.java
> +    public BakerySearchRequestDto(String city, String district, Set<Long> bakeryCategories, BakerySortType bakerySortType) {
빈 문자열에 대해서는 잘못된 Input이라 판단해서 BadRequest를 던지는게 맞다고 생각했었는데,
다른 파라미터들과 일관성을 위해서는 빈문자열 처리에 대해 고민해봐야겠네요..!
의견 감사합니다!

2022-02-08 13:21 UTC, younger-k commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
> +        throw new IllegalArgumentException();
오홍..! 상세하게 매세지 전달할 수 있도록 수정해두겠습니다!

2022-02-08 13:37 UTC, younger-k commented
안녕하세요 도영님!
꼼꼼한 리뷰 감사합니다 ㅎㅎ

1. 테스트코드에 대한건 다음 스프린트부터 반영이라 제가 착각했었나봅니다..ㅎ 리뷰 내용들 수정하면서 테스트코드도 작성해두겠습니다 ㅎㅎ

2. 흠.. 정렬같은 기능은 기본 요구사항이라 추후에 추가될 수도 있을 것 같아 확장 가능성을 열어두고 작업한거라 나중에 다른 정렬 기능이 추가될 땐 편하게 작업할 수 있지 않을까요?

3. 해결책 감사합니다 ㅠㅠ!! 회사에서 기본적으로 IntellijIDEA로 셋팅하고 쓰고있었습니다.. 이렇게 하나 배워갑니다 ㅎㅎ!

2022-02-08 14:27 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
> +        if (bakerySortType == BakerySortType.ID_DESC || bakerySortType == null) {
@younger-k 님 좋은 말씀 이네요. 말씀 주신 내용에 공감합니다.
Enum 은 원시적 타입 처럼 비교가 가능하니 기존 처럼 비교해도 괜찮을 것 같습니다 !

2022-02-13 06:49 UTC, younger-k commented
@doyoung0205 안녕하세요 도영님!
최신순 정렬 관련해서 피드백 반영했습니다.

1. `BakeryService.search` 최신순 정렬 테스트 코드 작성.
2. BakerySortType 공백 리퀘스트 허용.
3. BakerySortType 잘못된 input 요청 시 예외 핸들링
4. `findAllOrderByIdDesc()` 추가.

BakerySortType은 추후에 요구사항 추가 시 다시 사용하도록 남겨두었고, 현재는 `findAllOrderByIdDesc()` 메서드로 최신순 정렬만 실행되도록 하였습니다.

확인 부탁드립니다 😄

2022-02-13 17:41 UTC, doyoung0205 reviewed
@younger-k 연하님 안녕하세요 😄😄
findAllOrderByIdDesc 추가하신 내용과 테스트 코드 확인하였습니다 ! 👍🏻 

정렬에 대한 Enum 은 사용하지 않고 client 로 부터 매개변수로 받지 않아도 괜찮을 것 같은데,
현재 사용하지 않는 Enum 과 관련 로직은 삭제하는 것이 좋지 않을까요?

Enum 을 유지해야 한다면 Enum 에 대한 테스트 코드나 Enum 을 활용한 ServiceTest 테스트 코드 등이 추가되어야 할 것 같고, 
추후 변경사항이 생긴다면 관련 코드들을 수정해야 하는 관리 포인트가 많아지지 않을 까요?

2022-02-13 17:59 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +        assertTrue(response.get(0).getId() > response.get(1).getId());
초기에 셋팅 되는 데이터가 있다는 전재하에 작성된 테스트 코드 같네요 ! 
초기 데이터에 의존하지 않는 테스트 코드가 된다면 더 좋을 것 같습니다 !

2022-02-15 15:41 UTC, younger-k commented
> 

@doyoung0205 음.. 혹시 몰라 로직을 남겨두긴 하였는데, 관리 포인트를 생각하면 없애는게 맞겠군요!
제거해서 다시 올리도록 하겠습니다 😄

2022-02-16 02:00 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +        assertTrue(response.get(0).getId() > response.get(1).getId());
Bakery 가 등록되는 코드가 없는게 요인인것 같습니다.
현재 테스트 코드가 Bakery 초기 데이터 셋팅 되는 부분에 의존되는 부분을 없애주시면 좋을 것 같습니다 ! 

저 같은 경우에는 Repository 에서 구현한 findAllOrderByIdDesc() 는 따로 JpaDataTest 를 따로 테스트 만들고 
Service 로직은 BDD 로 Mockito 를 사용해서 행위를 테스트 했지만, 

연하님이 말씀주신 Map을 사용하는 테스트용 Repository 구현체를 만드는것 도 좋은 방법이라고 생각합니다 😆😆 

- [테스트 픽스처 참고자료](https://jojoldu.tistory.com/611)

2022-02-16 15:52 UTC, younger-k commented
@doyoung0205 안녕하세요 도영님!
Enum 관련 로직 제거하고 테스트 코드 다시 작성했스비다..
구두로 말씀하셨던 것처럼 Bakery가 거의 최종 Aggregate라.. 의존하는 서비스가 많다보니.. Mock 객체 return값 지정해주기가 빡씨네요..
뭔가 손으로 똥 싼 테스트 코드같지만.. 한번 확인 부탁드립니다 🥲

2022-02-17 02:31 UTC, doyoung0205 requested changes
고생많으셨습니다.
다음 스프린트때 테스트 픽스처 관련해서 다뤄보도록 하면 좋겠네요 ! 
일단 지금 사용하지 않는 IllegalSortTypeException 만 삭제 해주시면 될 것 같습니다 !

2022-02-17 13:39 UTC, younger-k commented
@doyoung0205 안녕하세요 도영님!
진짜 최종의 최종의 최종입니다...! 익셉션 제거했습니다 ㅎㅎ
리뷰들 감사합니다 😄

2022-02-18 03:32 UTC, doyoung0205 approved these changes
연하님 고생하셧습니다 ! 빠른 머지 하겠습니다 !

2022-02-18 03:32 UTC, merged