[UVNX-148] rest-assured 인수테스트 구성 & 인수테스트 DB 초기화 유틸 작성
endbreadkings/breadgood pull request #22
Opened 2022-02-13 06:56 UTC by haedoang

### 요약
인수 테스트 작성을 위한 [rest-assured](https://rest-assured.io/) 모듈 추가 및 샘플 테스트 코드 작성 & DB 초기화 유틸 작성

### 작업내역
1) UserAcceptanceTest
  - 회원 로그인 인수테스트 작성(샘플): 회원 관련 인수테스트는 추가로 티켓을 발급하여 진행할 예정

2) DatabaseCleanup util 
  - 인수 테스트 시 사용될 table, column 초기화 유틸 작성
  
3) 코드 리팩터링
 - 데이터 타입 오류 수정: User.socialLink 어노테이션 수정(`@Enumerated` -> `@Embedded`)
 - GenerationType  수정: RefreshToken GenerationType 수정(`AUTO` -> `IDENTITY`)
 - PK Column name 규칙화: user, withthrwal_user, refresh_token 수정(`table명_id` 규칙화)
 - Dto 수정: TokenRefreshResponse, LoginRequest 수정 (final 제거, default constructor, toString 추가)
 
 
### 작성자의 고민
1) 테스트 환경 설정의 분리: 테스트 코드는 h2 in-memory database를 사용하였기 때문에 환경 설정 분리가 필요할 것 같습니다. 차후
운영계 서버에 배포를 고려하면 (local, staging, prod, test) 네 개의 profile로 구성을 생각했습니다. local, staging, prod의 경우 database 연결 정보에 대한 부분만 변경될 것으로 예상되고, test 환경 설정은 in-memory 데이터베이스 설정정보로 구성을 생각했습니다. 현재 설정 파일 분리가 되어 있지 않아서 설정 파일을 어떻게 구성할지 이야기를 나눠보면 좋을 것 같습니다 

2) 테스트 픽스처 관련: 테스트 픽스처 가독성을 높이기 위해 sql 파일로 변경하는 것은 어떨까요? 
 
3) dto lombok 관련 : http  request test 시 post 요청 시 deserialize error 가 발생하여 default constructor를 추가하였습니다
 서버 내 배포되어있는 코드는 정상적으로 동작하는 것 같은데 원인이 뭘까요.. 🤔
 관련 내용 첨부 [링크](https://stackoverflow.com/questions/53191468/no-creators-like-default-construct-exist-cannot-deserialize-from-object-valu)
 
 4) h2database 취약점: h2 database가 v2.0 부터 많은 변경이 생겼다고 합니다. 현재 프로젝트를 2.0버전이상으로 사용할 시 변경할 사항이 많은데 관련 내용을 찾아보는 게 많이 어렵더라구요. 예를 들면 user 컬럼은 키워드기때문에 사용이 불가하다고 하는 등 기존 버전에서 동작하는 것들이 2.0버전에서 부터는 동작하지 않는 부분이 있습니다. 현재 다운그레이드한 상태이며, 해당 버전은 취약점을 가지고 있습니다.
```
[CVE-2022-23221](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23221)
[CVE-2021-42392](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42392)
[CVE-2021-23463](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23463)
``` 

- h2 database 쪽에 문의한 내용에 대한 답변
```
It is a keyword, you need to quote it as "USER" (or "user" if you use DATABASE_TO_LOWER=TRUE)
https://h2database.com/html/advanced.html#keywords

hibernate-core-5.4.9.Final also looks very suspicious, because Hibernate ORM supports H2 2.x.y only since the version 5.6.5.Final, you cannot use its older versions with recent versions of H2.
 ```
h2 2.0버전 사용 시 하이버네이트 버전도 변경이 필요해보입니다.

2022-02-13 08:55 UTC, doyoung0205 requested changes
해동님 진짜 고생많으셨습니다 ! 
어려웠던 점도 PR 에서 공유해주셔서 간접적으로 경험할 수 있어서 너무 좋았습니다. 


1. 리뷰어(다른팀원 분들 다)와 Assignees(자기자신) 를 추가해주시면 더 좋을 것 같습니다.
2. final 은 gradle build 하는 주체가 intellij idea 가 아니라 gradle 로 변경해주시면 해결될 문제일 것 같습니다.
[링크](https://github.com/endbreadkings/breadgood/pull/19#pullrequestreview-874059120)
3. h2 2.0 버전은 잠시 서랍속으로... ㅎ
4. 픽스처 관련된건 sql 파일로 가져가는 건 아직 공감이 조금 덜 되는 것 같습니다. 이 부분은 추후에 같이 이야기 나눠도 좋을 것 같아요 ! 
(다만, 스프링 컨텍스트가 띄어지면서 셋팅되는 데이터가 2가지 (초기 셋팅 데이터, 초기 더미 데이터) 가 있는데 초기 셋팅 데이터는 spring flyway sql 를 통해서 등록되면 좋을 것 같습니다 !

2022-02-13 08:55 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/ui/dto/TokenRefreshResponse.java
> +    private String tokenType = "Bearer";
파일 변경에 걸렸길래 여쭤봅니다..
tokenType 은 static 변수로 만드는 것 어떠신가욤?

2022-02-13 08:55 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserAcceptanceTest.java
> +
등록된 사용자는 초기에 셋팅 되는 더미데이터의 의존하지 않고
회원 등록 하는 부분을 추가하면 어떠신가요? 
```
회원_등록되어_있음(..); // 해당 메소드 추가 추천
```

2022-02-13 08:55 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/utils/DatabaseCleanup.java
> +            entityManager.createNativeQuery("alter table " + tableName + " alter column " + pkColumnName(tableName) + " restart with 1").executeUpdate();
깔끔하게 처리 됐네요 !! 💯💯

2022-02-13 14:50 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserAcceptanceTest.java
> +
🙇 테스트 픽스처를 구성하도록 하겠습니다

2022-02-13 14:51 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/utils/DatabaseCleanup.java
> +            entityManager.createNativeQuery("alter table " + tableName + " alter column " + pkColumnName(tableName) + " restart with 1").executeUpdate();
조언 주신 대로 변경하니 깔끔해졌습니다 👍

2022-02-13 15:31 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/ui/dto/TokenRefreshResponse.java
> +    private String tokenType = "Bearer";
@haedoang 님 
현재는 인스턴스(TokenRefreshResponse.java)가 만들어질 때마다 tokenType 에 대해서 새로 메모리를 잡고 초기화 과정을 겪을 텐데, 클래스 레벨에서 한 번만 잡아서 하나의 메모리 공간을 쭉 쓰게 된다면, 인스턴스 생성마다 매번 같은 메모리를 잡는 것(상수 풀)보다 더 효율적일 것 같습니다 ! 🤔🤔

AS-IS  ```private String tokenType = "Bearer";```
TO-BE  ```private static final String TOKEN_TYPE = "Bearer";```

1. Enum 은 상수가 여러개가 아니니까 괜찮을 것 같습니다. 🙏
2. lombok 설정 rollback 해도 괜찮을 것 같습니다 ! 👍🏻 👍🏻

2022-02-16 15:23 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/ui/dto/TokenRefreshResponse.java
> +    private String tokenType = "Bearer";
enum 으로 변경하였습니다 
configuration 쪽에서도 token type을 사용하여 공통화하고싶은데 의존성이 생기게 될까봐  고민이되네요

2022-02-18 03:44 UTC, doyoung0205 requested changes
고생하셨습니다 ! 
코멘트 확인 부탁드립니다 !

의존성이 어떻게 문제가 될 수 있는지 자세히 말씀 주시면 이해하는데 큰 도움이 될 것 같습니다 !

2022-02-18 03:44 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserAcceptanceTest.java
> +    }
요거는 삭제되도 괜찮을 것 같습니다 !

2022-02-18 03:44 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/domain/TokenType.java
> +    BASIC("Basic"),
BASIC 은 어떤 상황에서 사용하는 타입 인가요???

2022-02-22 15:04 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserAcceptanceTest.java
> +    }
아이고 ㅠㅠ 반영하도록하겠습니다 🙇

2022-02-22 15:06 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/domain/TokenType.java
> +    BASIC("Basic"),
인증 스킴에 대해 enum 으로 적용을 해두었습니다.  TokenType을 관리할 용도로 사용하려고 작성해두었습니다 (현재 사용하지는 않음)
차후 구현이 필요할 때 정의하는 것으로 변경하는게 나을까요~?

2022-02-22 15:30 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/domain/TokenType.java
> +    BASIC("Basic"),
넵 !! 차후에 구현이 필요할 때 추가되는 것이 좋을 것 같아요 !

2022-02-22 23:48 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/jwt/domain/TokenType.java
> +    BASIC("Basic"),
넵 수정완료했습니다 😄

2022-02-23 11:59 UTC, doyoung0205 approved these changes
해동님 고생하셨습니다 ! ㅠㅠ

2022-03-23 15:29 UTC, doyoung0205 approved these changes
안녕하세요 해동님. 
약관이랑 유저 그리고 인수테스트 작성까지 고생많으셨습니다.
꼭 변경이 필요한건 아니지만, 코멘트 한번 확인해주시면 감사하겠습니다 !

2022-03-23 15:29 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/termstype/fixtures/TermsTypeFixtures.java
> +    public static TermsTypeSaveRequestDto 필수약관1등록요청 =
요거는 사용하고 있는 코드인가용??

2022-03-23 15:29 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/termstype/fixtures/TermsTypeFixtures.java
> +    public static TermsTypeSaveRequestDto 필수약관1등록요청 =
- 픽스처 이름이  사용자 스토리에 맞게 `개인정보처리약관` 같은 이름도 괜찮다고 생각합니다.
- TermsType 도 약관 Terms 도 약관이네요 구분이 되면 좋을 것 같아요 !

2022-03-23 15:29 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/termstype/fixtures/acceptance/TermsTypeAcceptanceTest.java
> +                ));
약관_등록_되어있음(...); 같은 메서드를 만들어서 사용하면 좋겠지만, 아직 API 가 없어서 이렇게 적용해주신 것 같네요 ! 
인수테스트 흐름이 자연스럽기 위해 얼른 관리자 API 도 만들어야 겠네욤..

2022-03-23 16:14 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/termstype/fixtures/acceptance/TermsTypeAcceptanceTest.java
> +                ));
관리자 api가 없으니까 테스트가 번잡해지고 픽스처 구성 시 어려움이 많네요 😭  
연하님 도영님 한가해지시면 관련내용으로 회의진행하시면 좋을것같습니다~ 
인수테스트 만들면서 여러 도메인을 건드리다보니 수정사항이 많네욥

2022-03-24 06:10 UTC, younger-k approved these changes
안녕하세요, 해동님. 리뷰가 늦어져서 죄송합니다..ㅠㅠ
정말 고생 많으셨습니다 👏 👏 👏 
저도 아직 도메인에 대해 자세히는 몰라서 보면서 배워갑니다 👍 
작업하시면서 리팩터링까지 진행해주신점... 존경합니다 ㅎㅎ

테스트 픽스처를 저는 sql로 작성해서 사용하긴 하는데, 마이바티스를 쓰다 와서 그런지 별다른 이유 없이 그게 편해서 쓰던거라 어떤 방법이 더 좋을지는 논의해보면 좋을 것 같아요!

빠르게 Approved 하겠습니다 ㅎㅎ!

2022-03-24 06:10 UTC, merged