[빵집 리스트] 빵집 카테고리 조회 API 수정
endbreadkings/breadgood pull request #29
Opened 2022-02-17 14:11 UTC by younger-k

### 요약
1. 이미지 URL을 제공하도록 수정
2. 카테고리 컬러 코드 제공하도록 수정

### 작업내역
- 빵집 카테고리 조회 시, 카테고리 아이콘을 컬러이미지와 흰색 이미지 url & 컬러 코드를 함께 제공하도록 수정하였습니다.
- 웹뷰에서 카테고리별 별도 분기 처리 없이 카테고리 이미지와 컬러 코드를 사용하도록 수정하였습니다.

### 작성자의 고민
- NONE!

2022-02-18 03:56 UTC, doyoung0205 requested changes
안녕하세요 연하님 ! 

ImageUrl 적극적으로 활용해서 ValuObject 로 관리해주신점이 인상 깊었습니다. 😄 

### 궁금한 점
`titleWhiteImgUrl` 프로퍼티가 추가되었는데  어디서 사용되는지 알 수 있을까요?

2022-02-18 03:56 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakerycategory/domain/BakeryCategory.java
> +    private ImageUrl markerImgUrl;
@Embedded  어노테이션을 넣어줘야 하지 않을까용?

2022-02-18 12:49 UTC, younger-k commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakerycategory/domain/BakeryCategory.java
> +    private ImageUrl markerImgUrl;
아앗! 추가하도록 하겠습니다 ㅎㅎ

2022-02-18 12:52 UTC, younger-k commented
@doyoung0205 
카테고리 이미지가 카테고리 필터 활성화 여부에 따라 색상이 변경되어서 추가했습니다!
카테고리 필터가 활성화되면 배경색이 채워지고 아이콘이 하얀색으로,
카테고리 필터가 비활성화되면 배경색이 없어지고 아이콘이 색상이 채워진 상태로 변경되어야 합니다.

2022-02-18 13:08 UTC, younger-k commented
@doyoung0205 Embed 추가해서 수정 완료했습니다~

2022-02-18 21:23 UTC, doyoung0205 requested changes
titleWhiteImgUrl 을 사용하지 않는 줄 알았는데 사용하고 있었군욧 ! 
제가 제대로 보지 못했던 것 같습니다 ! 🤒 

나중에 요구사항이 꼭 활성화된 이미지가 꼭 하얀색 이미지가 아니라 다른색 이미지로 변경될 수 있을 것 같은데
titleWhiteImgUrl, titleColoredImgUrl 네이밍 보다  titleInactiveImgUrl, titleActiveImgUrl  어떠신가요?

2022-02-19 09:24 UTC, younger-k commented
@doyoung0205  안녕하세요 도영님!
active/inactive 네이밍도 생각을 했었는데 다음과 같은 이유로 제외했습니다.
네이밍만 봐서는 acitve가 컬러가 있는 이미지, inactive가 화이트 이미지가 들어가야 할 것 같지만..
실제 필터가 활성화 될 때에는 하얀색 이미지가 떠야해서 active에 하얀 이미지가 들어가게 되서 뭔가 어색하다고 생각이 됬었어요.

그런데 도영님 의견대로 하얀색이라고 고정하는 것도 좋지 못할 것 같네요..!
아니면,,, titleColoredImgUrl, titleUncoloredImgUrl은 어떨까 싶은데 도영님 의견은 어떠실까요?

2022-02-19 09:32 UTC, doyoung0205 commented
> @doyoung0205 안녕하세요 도영님! active/inactive 네이밍도 생각을 했었는데 다음과 같은 이유로 제외했습니다. 네이밍만 봐서는 acitve가 컬러가 있는 이미지, inactive가 화이트 이미지가 들어가야 할 것 같지만.. 실제 필터가 활성화 될 때에는 하얀색 이미지가 떠야해서 active에 하얀 이미지가 들어가게 되서 뭔가 어색하다고 생각이 됬었어요.
> 
> 그런데 도영님 의견대로 하얀색이라고 고정하는 것도 좋지 못할 것 같네요..! 아니면,,, titleColoredImgUrl, titleUncoloredImgUrl은 어떨까 싶은데 도영님 의견은 어떠실까요?


안녕하세요 연하님
제 생각은 프론트 코드를 보니 active 유무의 따른 이미지 를 보여주는 코드로 보여 
active/inactive 네이밍을 통일하는것이 좋지 않나 싶습니다 !

```
// as-is (현재)
{active ? category.titleWhiteImgUrl : category.titleColoredImgUrl}

// to-be
{active ? category.titleActiveImgUrl : category.titleInactiveImgUrl}
```


titleColoredImgUrl, titleUncoloredImgUrl 도 괜찮습니다 ! 
그렇다면 프론트 쪽에서도 isColor 로 변경해야하지 않나 싶습니다 ! (필요시 CSS 도..)


```
// 연하님 예시
{isColor ? category.titleColoredImgUrl : category.titleUncoloredImgUrl}
```

2022-02-19 09:51 UTC, younger-k commented
@doyoung0205 
카테고리 이미지를 `BakerySearchResponseDto`의 `categoryImgUrl`에도 사용중인데, **색상이 있는** 이미지를 리스트에 뿌려주어야 하기 때문에 색상이 있냐, 없냐로 네이밍을 지정하는 것이 좋을 것 같다 생각하여 colored, uncolored로 네이밍 정하는 방향으로 가겠습니다!

```java
this.categoryImgUrl = bakeryCategoryResponseDto.getTitleColoredImgUrl();
```

프론트 코드도 함께 `active` -> `isColor` 로 네이밍 변경하도록 하겠습니다 !

2022-02-19 09:55 UTC, younger-k commented
@doyoung0205 
앗.. 지금 코드 살펴보는데 프론트 코드는 active로 가야 할 것 같습니다..!
활성화 되었을 때, 배경색은 colored... 아이콘은 uncolored라서 isColor라는 네이밍이랑 맞지가 않습니다..ㅎ

active로 그냥 두었을 때, 활성화 시에는 배경색은 colored 아이콘은 uncolored라는 요구사항을 이해할 수 있지 않을까요?!

2022-02-19 10:11 UTC, doyoung0205 commented
> @doyoung0205 앗.. 지금 코드 살펴보는데 프론트 코드는 active로 가야 할 것 같습니다..! 활성화 되었을 때, 배경색은 colored... 아이콘은 uncolored라서 isColor라는 네이밍이랑 맞지가 않습니다..ㅎ
> 
> active로 그냥 두었을 때, 활성화 시에는 배경색은 colored 아이콘은 uncolored라는 요구사항을 이해할 수 있지 않을까요?!

그럴 수 있겠네요 ! 이해되었습니다 👍🏻

2022-02-19 10:17 UTC, younger-k commented
@doyoung0205 필드명 변경해서 올렸습니다..! 승인 부탁드립니다 🙇 
역시 네이밍은 정말 어렵네요 🥲 ..!

2022-02-19 11:11 UTC, doyoung0205 approved these changes
네이밍 진짜 어렵죠 .. 고생하셨습니다 연하님 👍🏻👍🏻

2022-02-20 12:39 UTC, haedoang approved these changes
고생하셨습니다 💯 👍

2022-02-20 12:41 UTC, merged