[UVNX-90] 빵집 등록 API 데이터 타입 변경 & 등록 validation 변경
endbreadkings/breadgood pull request #33
Opened 2022-03-20 08:39 UTC by haedoang

### 요약
- 빵집 등록 api 요청 시 시그니처메뉴 데이터타입 변경 @kyeonghyeon
- 빵집 등록 도시 validation 오류 수정

### 작업내역
- BakerySaveRequestDto 내 SignatureMenus 데이터타입 변경
  - as-is : `String`
  - to-be: `List<String>`
- BakeryService.validateSave() 도시 검증  validation 오류 수정

### 작성자의 고민
- 1) swagger로  multipart/form-data 테스트 안되는 이슈 
   :  swagger로 빵집 등록 api 테스트 시 파일 업로드 안되고, List 타입에 대해 테스트가 되지 않습니 
      개인 프로젝트 내 3.0 버전에서는 해당 이슈가 없어서 문의드립니다. 내용을 혹시 아신다면 공유부탁드립니다 🙏 
  => api 변경 테스트는 리퀘스트 시뮬레이팅 툴을 사용하여 검증하였습니다

2022-03-23 13:26 UTC, doyoung0205 requested changes
추후에 여러 형태의 서울이 있으면 복잡할 것 같아요.
큰 지역인 서울 일 경우에 `서울특별시` 로만 받는 것 어떠신지 궁금합니다.

2022-03-23 13:26 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
> +            if (StringUtils.isEmpty(dto.getCity()) || !dto.getCity().equals(SEOUL_CITY_WORD) && !dto.getCity().contains(SEOUL_WORD)) {
`서울특별시` 만 받을 수 있도록 하면 좋을 것 같아요. 지금은 서울로 시작하는 단어가 전부 가능 하게 되는 거니까..

2022-03-23 14:05 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    @Embedded
👁️ 👁️

2022-03-23 15:13 UTC, doyoung0205 requested changes
한동님 고생하셨습니다.
의견 몇개 만 더 드립니다 !

2022-03-23 15:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +        BakeryCategory category2 = 카테고리2();
픽스처가 메서드인 이유가 있을까요? static 변수도 괜찮을 것 같습니다.

2022-03-23 15:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +    @ValueSource(strings = {"대구광역시", "강원도", "서울시 마포구", "서울", "서울시 광진구"})
크으 👍🏻 👍🏻

2022-03-23 15:13 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
> -        if (StringUtils.isEmpty(dto.getCity()) || !dto.getCity().equals(SEOUL_CITY_WORD) || !dto.getCity().contains(SEOUL_WORD)) {
혹시 SEOUL_WORD 변수도 제거 하신걸까요?

2022-03-23 15:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/fixtures/BreadStyleFixtures.java
> +public class BreadStyleFixtures {
최애빵 스타일은 이미 픽스처가 존재합니다. developer 브랜치에서 따오셔도 괜찮을 것 같아요 !

2022-03-23 15:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/bakerycategory/fixtures/BakeryCategoryFixtures.java
> +    public static BakeryCategory 카테고리1() {
빵집 카테고리 픽스처도 현재 PR 중이긴 한데, 다행히 클래스이름이 달라서 충돌나진 않겠네요!

2022-03-24 06:37 UTC, younger-k requested changes
해동님 고생하셨습니다! 간단한 질문 드렸는데 이거만 확인 부탁드릴게요 👀

2022-03-24 06:37 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +        BakeryCategory category2 = 카테고리2();
엇 이건 저도 궁금하네요...!

2022-03-24 06:37 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/fixtures/BakeryFixtures.java
> +        )
@haedoang 스웨거 켜보고 싶어서 체크아웃 받아서 빌드했는데 
여기서 세미콜론 없어서 에러나는데,, 다른 분들은 괜찮으신가요?

2022-03-24 10:43 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/fixtures/BakeryFixtures.java
> +        )
저도 컴파일 오류가 발생하네욧 !

2022-03-26 05:19 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/application/BakeryServiceTest.java
> +        BakeryCategory category2 = 카테고리2();
기대와 달리 아무 이유없었습니다.. 🙇  
불변 객체로 변경하였습니다!

2022-03-26 05:20 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
> -        if (StringUtils.isEmpty(dto.getCity()) || !dto.getCity().equals(SEOUL_CITY_WORD) || !dto.getCity().contains(SEOUL_WORD)) {
아니요 ! 
다른 로직에서 사용할 수 있을 것 같아서 조건문에서만 제외하였습니다~

2022-03-26 06:15 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/fixtures/BreadStyleFixtures.java
> +public class BreadStyleFixtures {
픽스처 병합 후 
패키지 따로 분리하였습니다~~
as is 도메인 내 fixture 패키지
to be com.beside.breadgood.fixtures

2022-03-26 06:17 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/bakery/fixtures/BakeryFixtures.java
> +        )
확인하였습니다 🙇

2022-03-27 08:43 UTC, doyoung0205 approved these changes
고생하셨습니다 해동님 ! 👍🏻 👍🏻

2022-03-27 08:43 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/fixtures/termstype/TermsTypeFixture.java
>  }
요거는 사용하지 않는 함수 인것 같네용 !ㅎㅎ

2022-03-27 11:10 UTC, younger-k approved these changes
고생 많으셨습니다 👍 👍 👍

2022-03-27 12:00 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/fixtures/termstype/TermsTypeFixture.java
>  }
그렇군요!  차후 리팩토링 시 미사용하게되면 제거하겠습니다

2022-03-27 12:00 UTC, merged