UVNX-191 관리자 로그인 기능 구현
endbreadkings/breadgood pull request #41
Opened 2022-04-19 16:00 UTC by haedoang

### 요약
- 관리자 로그인 기능 구현 
- 테스트 코드 오류 수정 

### 작업내역
- 관리자 로그인 기능 구현 (/manage/user )
- 관리자 로그인 validate(Role 구분 추가, status 400, IllegalRoleException, -1303)
- 사용자 로그인 실패 에러코드 수정 (UserNotFoundException, 500 -> 400)
- 실패된 테스트 코드 수정 및 테스트 픽스처 수정 
-  initData environment 구분 프로파일 지정 ("!test")
- mysql docker config 수정 

### 작성자의 고민
1. 테스트 픽스처 사용에 대한 고민 
  도메인 객체의 테스트 픽스처 사용 시 여러 테스트 케이스에서 사용할 경우 PK값이 지정되는 문제가 발생하여 기존 테스트 실패가 발생하는 경우가 있어서 수정하였는데요 어떻게 조치하면 좋을지 의견을 나누고 싶습니다
   생각 : 메서드로 호출 시 테스트 픽스처 객체를 생성한다 (현재는 정적 필드로 사용하고 있음). 좋은 의견 주시면 감사하겠습니다!! 🙇 
   
 2. 도메인 객체의 생성자의 PK 포함 여부
   현재 구현되어 있는 도메인 중 PK값을 포함하는 객체도 있고 그렇지 않은 객체도 존재합니다. 통일되었으면 하고 그로 인해 PK 포함 여부를 어떻게 할지 궁금합니다. 
    생각: 테스트 시 PK 누락으로 인한 처리에 대해 필요한 경우가 있음. 테스트 시 사용에 불편함이 있지만  테스트에서만 사용되기때문에 없어도될 것이라 생각함. 관련하여 pk를 리플렉션으로 주입할 수 있는 정적 메서드를 구현해두었음 `com.bside.breadgood.fixtures.TestUtils` 
    
3. 관리자 컨트롤러 분리의 범위 
  현재 컨트롤러만 분리하였으며, 예외 핸들링의 Advice는 따로 구분하지 않았습니다. 이유인 즉슨 UserNotFoundException 같이 중복될 수 있는 예외처리 때문이었는데요. 어떻게 생각하시는지 공유 부탁드립니다 🙇 
  
4. 저는 한번 브랜치 따면 이것저것 수정하게 되어 보기 힘들게 해드려 죄송합니다. 브랜치 생성 이유와 연관되지 않은 작업이 연결되는 경우 따로 브랜치를 분리하시는 지 조언 부탁드립니다 🙇

2022-04-20 04:13 UTC, doyoung0205 requested changes
해동님 고생 많으셨습니다. 🙇🏻🙇🏻 

몇개의 코멘트 남겨 드렸습니다. 확인 부탁드리겠습니다.

---


> 1. 테스트 픽스처 사용에 대한 고민

말씀 주신대로 `메서드로 호출 시 테스트 픽스처 객체를 생성하는 것` 이 좋을 것 같습니다 !


> 2. 도메인 객체의 생성자의 PK 포함 여부

PK 로 equals 나 hashcode 가 구현되니  PK 를 넣지 않을 수 없으니.. 저도 이게 고민이네요.
PK 가 포함된 생성자를 private 으로 넣고 `getFakeInstance` 같은 정적 팩토리 메서드를 만드는 것도 방안이 될 수 있을 것 같습니다.


> 3. 관리자 컨트롤러 분리의 범위

- 모듈로 나누는 것이 좀더 좋다고 생각합니다. 왜냐하면 관리자 전용 API 서버,  Client API 서버를 따로 둘 때 모듈로 나눠져있으면 관리하기 편하다고 생각하기 때문입니다.
- `UserNotFoundException` 재사용하신것 좋다고 생각합니다.

> 4. 브랜치 

저도 비슷한 고민을 많이 합니다. 
JIRA 티켓과 매칭하는 것 이 중요하다고 생각해서 해당 브렌치에 관한 내용만 작성하려고 따로 브렌치를 나눠서 작업합니다.

2022-04-20 04:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/fixtures/TestUtils.java
> +    public static <T> void setId(T t, Class<T> clazz) {
현재는 setId 가 무조건 1L 로 셋팅 되는데 외부로 주입 받게 하면 어떨지 궁금합니다.

2022-04-20 04:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/fixtures/TestUtils.java
> +    public static <T> void setId(T t, Class<T> clazz) {
해당 코드에 대한 테스트 코드가 있으면 좋을 것 같아요 !

2022-04-20 04:13 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserManageAcceptanceTest.java
> +public class UserManageAcceptanceTest extends AcceptanceTest {
크으 인수테스트 깔끔하게 잘 만들어주셨네요 ! 🥇

2022-04-20 04:13 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserManageController.java
> +@RequestMapping("/api/v1/manage/user")
`com.bside.breadgood.ddd.users.domain.Role` 에서 관리자라는 명칭을 ADMIN 으로 사용하고 있어서 사용하신 manage 가 혼란이 될 수 있을 것 같아욧 !

user 대신 admin 으로 하는 것은 어떠신가요? 

// AS_IS 
`/api/v1/manage/user`

// TO_BE
`/api/v1/admin`

2022-04-20 04:13 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserControllerAdvice.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
저의 실수를 수정해주셔서 감사합니다 !! ㅎㅎ

2022-04-20 11:48 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserManageController.java
> +                                authority.getAuthority().equals("ROLE_ADMIN")
validator를 사용하면 좋을 것 같군요!

2022-04-20 11:51 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/fixtures/TestUtils.java
> +    public static <T> void setId(T t, Class<T> clazz) {
단위테스트를 추가해보도록 하곘습니다. 
PK를 입력받도록 아규먼트를 추가하는 게 좋겠군요!

2022-04-20 11:52 UTC, haedoang commented on docker/mariadb/conf.d/my.cnf
> +default-time-zone='+9:00'
default-time-zone 설정이 기존대로 진행하면 컨테이너가 정상적으로 실행이 되지 않아서 변경하였는데
혹시 도영님이나 연하님은 어떠신가요 ? 확인해주실수 있으신가요 ? 🤔
@doyoung0205  @younger-k

2022-04-20 11:58 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserManageController.java
> +@RequestMapping("/api/v1/manage/user")
도메인 단위로 manage 컨텍스트를 앞에 붙였는데 
관리자 사용자 도메인 컨텍스트 => `/api/v1/admin/user`
관리자 약관 도메인 컨텍스트 => `/api/v1/admin/termsType` 

제가 이해한게 맞을까요~? 

그리고 또하나 질문이 있네요 🙇  uri에 대문자는 안티패턴으로 알고 있어서 찾아봤습니다.

https://stackoverflow.com/questions/13511227/url-structure-lower-case-vs-upper-case

2022-04-25 14:15 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +        //FIXME 내용 문의하기
아 이부분 문의드리려했는데! 깜빡했네요!!

2022-04-26 04:43 UTC, doyoung0205 requested changes
안녕하세요 해동님 ! 고생많으셨습니다.

이전 리뷰 내용중 2번 내용에 대한 생각이 어떤지 궁금합니다.
리플렉션을 이용한 setId 를 사용하는것과 
생성자를 이용한 Fake 객체를 사용하는 것에 대해서 입니다.

2022-04-26 04:43 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/config/SecurityConfig.java
>                  .antMatchers("/api/v1/user/social/signup").hasRole(Role.GUEST.name())
아래 코드가 추가되면 어떨지 궁금하네욧 !
.antMatchers("/api/v1/admin/**").hasRole(Role.ADMIN.name())

2022-04-26 04:43 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +        //FIXME 내용 문의하기
어떤 문의 인가용?

2022-04-26 04:43 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/infra/AdminAuthenticationValidator.java
> +public class AdminAuthenticationValidator {
내부 자원을 사용하는 것이 없는데 유틸성 클래스가 아닌 빈으로 만든 이유가 있을까요?

빈으로 만든 다면,
AuthenticationManager 매개변수로 받지 말고 빈으로 주입받아 인스턴스 변수로 사용하시는 것은 어떤가요? 


public class AdminAuthenticationValidator{

AuthenticationManager authenticationManager;

public Authentication validate(LoginRequest loginRequest) {
  ...
}
}

2022-04-26 04:43 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/infra/InitUserData.java
> +        add("관리자", "manager@breadgood.com", password, 1L, userTermsList, Role.ADMIN);
여기도 manager 대신 admin 으로 용어 통일 하면 좋겠네요 !

2022-04-26 04:43 UTC, doyoung0205 commented on docker/mariadb/conf.d/my.cnf
> +default-time-zone='+9:00'
엇 저는 기존것으로 도 잘 실행 되고 있었습니다. 혹시 @younger-k 님은 어떤가요?

2022-04-26 15:58 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>              throw new EmptyException("빵집 카테고리 값이 없습니다.");
여기 조건 이렇게 구현되어있는 이유를 몰라서 주석 남겨두었는데 확인가능하실까요???

2022-04-26 15:59 UTC, haedoang commented on docker/mariadb/conf.d/my.cnf
> +default-time-zone='+9:00'
연하님 확인해주시면 처리하겠습니다~~ 제PC문제인가요 😭

2022-04-26 16:08 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/infra/InitUserData.java
> +        add("관리자", "manager@breadgood.com", password, 1L, userTermsList, Role.ADMIN);
수정하겠습니다

2022-04-27 02:30 UTC, doyoung0205 approved these changes
해동님 늦은시간까지 고생 많으셨습니다. 🥇 🥇 
열심하시는 것 같아서 저도 더 열심히 하게 되네욧 ! 👍🏻 

PS. 여유가 있으시다면 스프린트가 끝나고나서 fake 객체에 대해서는 이야기를 좀더 나눴으면 좋겠습니다 !

2022-04-27 02:30 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>              throw new EmptyException("빵집 카테고리 값이 없습니다.");
조건이 빵집 카테고리가 없을 경우 말씀하시는 건가요? 아니면 좌표가 없을 경우를 말씀하시는 건가요?

- 좌표, 빵집 카테고리가 필수 조건이라 그렇습니닷 !

2022-04-27 02:30 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/config/SecurityConfig.java
>                  .antMatchers("/api/v1/user/social/signup").hasRole(Role.GUEST.name())
허걱 그렇군요 ! 알겠습니닷

2022-04-27 12:16 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>              throw new EmptyException("빵집 카테고리 값이 없습니다.");
아하 제가 너무 설명없이 질문을 드렸었네요 🙇  
확인감사합니다 위에 주석 내용은 제거하도록 하겠습니다

2022-05-01 10:47 UTC, younger-k requested changes
해동님..! 우선 리뷰가 너무 늦어져 죄송합니다 😭 😭 
코멘트 남긴 한 가지만 확인 부탁드릴게요!

정말 고생 많으셨습니다 👍 👍 👍

2022-05-01 10:47 UTC, younger-k commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserControllerAdvice.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
IllegalRoleException이 권한이 없는 유저의 접근일 경우 발생하는 예외인 듯 싶은데,
이럴 경우 400 BadRequest보단 403 Forbidden이 맞지 않을까요?

2022-05-01 11:26 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/users/ui/UserControllerAdvice.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
오 저도 공감합니다! 수정하는 게 좋을 것 같아요!

2022-05-01 11:37 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/users/acceptance/UserManageAcceptanceTest.java
> +    public static final String USER_BASE_URI = "api/v1/admin";
연하님 덕분에 오류를 찾았네요! 변경된 context로 수정하였습니다

2022-05-01 11:42 UTC, younger-k approved these changes
해동님 빠른 확인 감사합니다 😄  💯 💯 💯 
빠르게 approve 하겠습니다 👍

2022-05-01 11:46 UTC, merged