[UVNX-188] 관리자 최애빵 생성하기 API
endbreadkings/breadgood pull request #50
Opened 2022-06-02 14:36 UTC by younger-k

### 요약
- 관리자 최애빵 생성하기 API

### 작업내역
- 관리자용 최애빵 등록 API 추가
- 관련 테스트 코드 추가
- 요청 DTO의 spring validation 실패 시 발생하는 BindException 관련 공통 예외 처리  추가

### 작성자의 고민
 지난번에 도영님도 같은 고민을 하셨던거 같은데... 🤔  
 인수 테스트 시에 실제 S3에 파일을 업로드 하고 마지막에 테스트 코드로 인해 업로드된 파일은 삭제하는게 맞을까요?

2022-06-05 12:07 UTC, doyoung0205 requested changes
연하님 고생하셨습니다. 소소한 코멘트 남겨드렸습니다 확인부탁드립니다.

파일 테스트 같은 경우 저도 서버로 직접올려서 테스트를 하기로 했는데, 실제 운영에서 업로드 한 파일이랑 겹처서 겹처쓰기만 안되면 삭제안해도 괜찮을 것같아요 !

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +  public ExtractableResponse<Response> 최애빵_등록_요청(String token,
이왕 public 이라면 static 으로 만들어 유틸성으로 사용할 수 있도록 하는 것이 좋을 것같은데 어떻게 생각하시나요?

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    최애빵_등록_성공(response);
어떤건 영어 어떤건 한글이네요 ! 
인수테스트는 개발자 뿐만아니라 다른 파트에 분들이 봤을 때도 이해할 수 있도록 코드를 짜는 것이 좋다고 생각해요.
저랑 해동님은 한글로 통일해서 작성하고 있어요

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
혹시 이 어노테이션을 사용한 이유가 있을까요?

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/breadstyles/ui/dto/BreadStyleRequestDto.java
> +  @ApiModelProperty(value = "최애빵 이름", example = "매콤")
꼼꼼하게 잘 만들어주셨네요 ! 크으 👍🏻 👍🏻

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminController.java
> +      @Valid BreadStyleRequestDto requestDto,
@Valid 어노테이션으로 UI 단에서도 유효성 검사를하셨네요 ! 좋네요 ! 👍🏻

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/breadstyles/infra/BreadStyleRepository.java
> +    @Query("select coalesce(max(b.sortNumber), 0) from BreadStyle b")
coalesce 함수를 쓰셨네요 ! 굳굳 !

2022-06-05 12:07 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
300 으로 무조건 검사하는 건 꺠지기 쉬운 테스트 검증 코드가 될 것같아요 !

2022-06-05 13:12 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
테스트 라이프 사이클 자체를 메서드에서 클래스로 변경하여 초기 세팅을 메서드마다 진행하는 것이 아니라 클래스 파일 실행 시 1번으로 적용시키려다 보니 순서를 지정하지 않으면 테스트가 통과되지 않는 경우가 발생하여 추가했습니다!

`@TestInstance(Lifecycle.PER_CLASS)`의 경우 `@Order`를 사용하려면 `@TestMethodOrder`를 추가해주어야 한다고 하네요.
- [관련 블로그](https://effortguy.tistory.com/120)
- [Junit @TestMethodOrder 문서](https://junit.org/junit5/docs/5.5.0/api/org/junit/jupiter/api/TestMethodOrder.html)

2022-06-05 13:15 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +  public ExtractableResponse<Response> 최애빵_등록_요청(String token,
아하 그럴 수도 있겠네요..! 
다른 곳에서도 사용할 수 있도록 static으로 변경해두겠습니다 👍

2022-06-05 13:20 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
초기 데이터(`100`,` 200`)에서 추가 되었을 때 다음 정렬 번호인 `300`이 인수 테스트에서도 잘 적용 되는지 확인해보고 싶어서 추가한 코드였습니다.
검증이 깨질까봐 `@Order`로 테스트 순서를 지정하는 방향으로 진행하였는데, 그래도 문제가 발생하는 경우가 있을까요..?

2022-06-06 01:53 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
어떤 reponse 가 와도 정렬번호가 300 을 검증하는 코드인 것 같아서요 ! 
차라리 request 부분도 매개변수에 추가해서 request. getSortNumber + 100 equalsTo response.getSortNumber 와 같이 검증하는 것이 어떠신가요? 

그리고 Order 에 대해서도 한번 생각해보면 좋을 것같아요. 
순서가 중요한테 테스트코드가 있다는건 테스트 간에 서로 영향을 주는 상황이 있다는 것인데 
저는 이 부분이 좋은 테스트 코드인지 고민이 되네요 ! 

저번에 링크드린 블로그에 대해서도 언급 되는 것 같은데 이 부분에 대해서 연햐님 생각이 궁금하네욧

2022-06-06 01:54 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
오오 그렇군요 !!
제생각은 [요기 코멘트](https://github.com/endbreadkings/breadgood/pull/50#discussion_r889773806) 참고 부탁드려욧 !

2022-06-06 02:16 UTC, doyoung0205 requested changes
연하님 고생하셨습니다. 빠른리뷰 반영 고생많으셨습니다 👍🏻 👍🏻 
아직 스프린트 여유도 있고 테스트코드 관련해서 연하님 생각이 궁금하여 한번 더 의견나누고 가면 좋을 것 같아용

2022-06-06 02:16 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
@cc @haedoang

2022-06-06 02:17 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
cc. @haedoang

2022-06-06 05:39 UTC, younger-k commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
흠.. 도영님 말씀처럼 해석될 여지가 많네요! 좋은 리뷰 감사합니다 👍 

기존의 코드처럼 한 테스트 클래스 파일 내의 모든 메서드마다 똑같은 setUp을 진행하는 것이 비효율적이라 생각하여 클래스 단위로 setUp을 진행하도록 하다보니 테스트 메서드 간 결합도가 발생하게 된 것 같습니다 😢 

사용자 등록과 같이 기본적으로 모든 테스트 메서드에서 필요한 셋업은 테스트 클래스당 1번 일어나도록 하고,
테스트간 결합 문제를 일으킨 BreadStyle에 대한 셋팅은 [일전에 알려주신 블로그](https://jojoldu.tistory.com/611)처럼 팩토리를 사용하여 각각의 테스트 메서드 내에서 필요에 따라 사용하도록 하는게 효율적일듯 싶은데 어떻게 생각하시나요?!

괜찮으면 위 방법으로 수정해볼까 합니다!

2022-06-06 14:26 UTC, haedoang approved these changes
테스트 작성하시느라 고생많으셨습니다

2022-06-06 14:29 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    최애빵_등록_성공(response);
공유 드리지 못한 내용이네요 🙇

2022-06-06 14:31 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
죄송해요 놓쳤네요;; 
제 생각은 인수테스트 검증 메서드로 `최애빵_등록_성공()` 으로 작성하셨으니 `expectValue` 값을 파라미터로 줘도 괜찮을 것 같습니다.
given  절에 기대값을 선언하고 메서드 호출 시 비교해도 괜찮을 것 같아요

2022-06-06 16:22 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/breadstyles/ui/BreadStyleAdminAcceptanceTest.java
> +    assertThat(responseDto.getSortNumber()).isEqualTo(300);
좋은 생각으로 느껴지네요 연하님 ! 응원합니다 !

2022-06-08 14:41 UTC, younger-k commented
@doyoung0205 @haedoang 
인수테스트 관련 리뷰내용들 반영해보았습니다! 확인 부탁드립니다 🙇 

setUp은 클래스 내에서 한번만 이루어지며 모든 테스트에서 공통으로 필요로하는 관리자 등록과 토큰 발급이 진행됩니다.
이 후 테스트에 필요한 최애빵 데이터는 테스트 메서드 내의 given절에서 생성하여 사용하며 테스트 이후엔 삭제를 진행하여 다른 테스트들에 영향을 끼치지 않도록 작성해보았습니다.

PS. setUp 과정에서 사용자 등록 시에 최애빵 스타일이 필요해서.. 추가를 하자니 다른 최애빵 테스트들에 영향이 가는 것 같아 그냥 사용자 등록 후에 삭제해주는 방향으로 작성하였습니다.. 🥲 따로 유저에 최애빵에 대한 외래키가 걸려있지 않아 삭제가 되긴 하는데 괜찮은걸까요..?

2022-06-11 10:16 UTC, doyoung0205 approved these changes

2022-06-11 10:17 UTC, doyoung0205 commented
> PS. setUp 과정에서 사용자 등록 시에 최애빵 스타일이 필요해서.. 추가를 하자니 다른 최애빵 테스트들에 영향이 가는 것 같아 그냥 사용자 등록 > 후에 삭제해주는 방향으로 작성하였습니다.. 🥲 따로 유저에 최애빵에 대한 외래키가 걸려있지 않아 삭제가 되긴 하는데 괜찮은걸까요..?

유저 등록할 때 필요한 최애빵 스타일을 삭제 하지 않고 테스트들에 영향을 주지 않도록 짤 수 있으면 베스트일 것 같긴한데 이런 작성이 어려운 점이 있을까요?

2022-06-11 11:44 UTC, younger-k commented
@doyoung0205 음.. 최초 최애빵 스타일 등록 시에 정렬 번호가 100으로 잘 들어가는지에 대해 확인하는 테스트 케이스를 작성해서,
setUp에서 유저 등록 시에 저장한 최애빵 스타일을 삭제해주고 있습니다 😢 

이 부분에 대해서는 어떤 것이 Best practice 일지 조금 더 고민해보겠습니다 🤔

2022-06-11 11:47 UTC, doyoungkim-29cm commented
> @doyoung0205 음.. 최초 최애빵 스타일 등록 시에 정렬 번호가 100으로 잘 들어가는지에 대해 확인하는 테스트 케이스를 작성해서, setUp에서 유저 등록 시에 저장한 최애빵 스타일을 삭제해주고 있습니다 😢
> 
> 이 부분에 대해서는 어떤 것이 Best practice 일지 조금 더 고민해보겠습니다 🤔

최근 등록된 최애빵 스타일을 조회해서 비교하는 방법은 어떠신가요? 🤔
그리고 인수테스트에서 테스트하기 어려운 것들은 도메인 레이어에서 자세히 테스트 하는 방법도 있을 것 같아요.

2022-06-11 11:55 UTC, younger-k commented
> 최근 등록된 최애빵 스타일을 조회해서 비교하는 방법은 어떠신가요? 🤔 그리고 인수테스트에서 테스트하기 어려운 것들은 도메인 레이어에서 자세히 테스트 하는 방법도 있을 것 같아요.

오! 좋은 의견 감사합니다 👍 
그렇다면 최초 등록과 관련된 내용은 인수테스트에선 제외하고 서비스나 레파지토리 영역에서 자세히 테스트 하면 될 듯 싶습니다!

2022-06-11 12:07 UTC, younger-k commented
아무래도 테스트 라이프 사이클을 클래스 단위로 두는건, 각각의 테스트 메서드들 사이에 의존성이 생길 수 밖에 없을 듯 하여 제거했습니다 🥲 
역시 써봐야 뭐가 단점인지 명확해지네요..ㅎ

우선 이슈는 머지하도록 하겠습니다!

2022-06-11 12:07 UTC, merged