[UVNX-185] 빵집 리뷰 삭제 기능 구현
endbreadkings/breadgood pull request #64
Opened 2022-06-14 17:29 UTC by haedoang

### 요약
빵집 리뷰 삭제 기능 구현 

### 작업내역
빵집 관련 테스트 코드가 없어서 추가했습니다 😓  
리뷰 삭제 관련 기능을 추가하였습니다 
리뷰Id를 view에서 사용할 수 있도록 response 에 추가하였습니다 
오류메시지 수정 
### 작성자의 고민
- `soft delete` 기능을 구현하였을 때 cascade 엔티티 성능 이슈
현재 `orphanremoval` 옵션으로 삭제 로직을 구현하였는데 문제가 되는 점은 두 가지입니다
1. `Bakery` 엔티티 삭제 시 `BakeryReview` 엔티티의 `update query` 가 N개 발생합니다 
 -> bakery 삭제 시 bakeryReview 의 외래키를 참조하여 일괄 업데이트 하는 `jpql` 쿼리 작성을 생각해보았습니다 
2. cascade 옵션으로 인하여 리뷰 삭제 시 업데이트 쿼리가 2번 발생합니다 
  ```sql
  -- 1. 외래키 컬럼을 제거하는 업데이트쿼리 
     update
          bakery_review 
      set
          bakery_id=null 
      where
          bakery_id=? 
          and bakery_review_id=?
  -- 2.soft delete 실행 쿼리
    UPDATE
          bakery_review 
      SET
          deleted = true,
          bakery_id=null 
      WHERE
          bakery_review_id=?        
  ```
-> 1번 이슈에서처럼 `BakeryReview` 서비스에서 처리하는 방법을 생각해보았습니다

2022-06-14 17:34 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>      @JoinColumn(name = "bakery_id")
리뷰 삭제 기능의 사용을 위해 추가하였습니다
cascade 옵션을 변경해도 고민했던 부분은 동일하더군요 🤔

2022-06-14 17:35 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
계원님, 도영님과 회의를 통해서 최초등록자의 리뷰의 삭제는 불가하도록 구현하였습니다.

2022-06-14 17:37 UTC, haedoang commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/utils/EntityReflectionUtils.java
> +    }
도메인의 연결이 강하게 되어있어서 테스트코드 작성에 어려움이 많네요 
테스트 코드 작성을 수월하게 하고자 리플렉션을 통해 필드값을 주입할 수 있도록 추가해보았습니다

2022-06-15 08:42 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
>              bakery.addBakeryReview(userService.findById(5L), "소보루 존맛 소보루 존맛 !!", emojiService.findById(2L), List.of("MjAxOTEwMDlfNTQg/MDAxNTcwNjAyOTkyNDc4.0YQy3to-9ap_Hk_YHBoWra1_sVDGnPtqrK7tstchhE8g
리뷰 추가 부분에서 그런 validation 이 없으면 원래 2건 추가 가능한것 아닐까요..?

2022-06-15 08:42 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
>              bakery.addBakeryReview(userService.findById(5L), "소보루 존맛 소보루 존맛 !!", emojiService.findById(2L), List.of("MjAxOTEwMDlfNTQg/MDAxNTcwNjAyOTkyNDc4.0YQy3to-9ap_Hk_YHBoWra1_sVDGnPtqrK7tstchhE8g
훔냥

2022-06-15 08:43 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>      @JoinColumn(name = "bakery_id")
orphanRemoval = true 이면 고아 객체만들려면 cascade = CascadeType.ALL 이지 않아도 되지 않나용??

2022-06-15 08:44 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
최초 등록자의 첫번째 리뷰를 삭제 불가하도록 구현 변경 가능한지 여쭤보고 싶습니다 !

2022-06-15 08:46 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
정확히 맞습니다만 .. 기존에 있던 BakeryWebViewController 나 BakeryWebViewAdminController 에 구현하면 조금더 좋을 것 같습니다..

2022-06-15 08:54 UTC, doyoung0205 requested changes
해동님 결국 해내셨군요 대단하십니다! 
SOSO한 코멘트 확인 한번 부탁드릴게요!

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
무조건 반환해야 하는 메서드라면 getReview 가 어떠신가요?

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +                .findFirst()
findFirst 보다 findAny 를 사용하는것이 더 좋다고 합니다 !

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/BakeryReview.java
>  public class BakeryReview extends BaseEntity {
Equals And Hashcode 구현되어있나요? 구현되어있다면 Id 만 타겟하면 좋을 것 같습니다!

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/BakeryReview.java
> +    @Embedded
크으 드디어 수정되네요 ㅋㅋㅋㅋㅋ

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/BakeryReview.java
> +                .collect(Collectors.toList());
보기 좋아욧! 그래도 domain 에서 바깥으로 나가는 거는 수정불가능한 Collection 이면 더 좋을 것 같아요!

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +        return super.getExceptionResponse(request, messagePath, ex.getMessage());
수정하신 이유가 있으실까요?
혹시 테스트 해보셨을까요?

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +import com.bside.breadgood.ddd.bakery.application.exception.*;
* 말고 개별로 쓰는게 더 좋은 것 같아요!

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
혹시 여기에 또 구현한 이유가 있으실까요?

2022-06-15 08:54 UTC, doyoung0205 commented on breadgood-server/src/test/java/com/bside/breadgood/ddd/utils/EntityReflectionUtils.java
> +    }
흠.. 뿌앵

2022-07-03 09:28 UTC, younger-k approved these changes
너무 늦어서 정말 죄송합니다ㅠ_ㅠ...
고생 많으셨습니다 해동님!

고민하신 내용에 대해 찾아보았는데,
1. Bakery 엔티티 삭제 시 n개의 업데이트 쿼리 발생은.. 별다른 옵션값을 찾진 못하였습니다 🥲 해동님 말씀대로 jpql로 해결해야 할 듯 싶습니다.
2. 제가 제대로 이해한게 맞는진 모르겠는데 현재 코드가 bakery에서 cascade를 이용하여 리뷰를 삭제해서 발생하는 문제가 맞다면, 해동님 말씀대로 리뷰 서비스에서 따로 해결해야 할 듯 합니다. 혹시 Bakery 도메인에서 처리하신 이유가 따로 있는건지 궁금하네여.. 🤔

2022-07-06 12:36 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/application/BakeryService.java
>              bakery.addBakeryReview(userService.findById(5L), "소보루 존맛 소보루 존맛 !!", emojiService.findById(2L), List.of("MjAxOTEwMDlfNTQg/MDAxNTcwNjAyOTkyNDc4.0YQy3to-9ap_Hk_YHBoWra1_sVDGnPtqrK7tstchhE8g
게시글에  본인 리뷰를1개만작성할수 있는걸로 이해했는데 아닌가요?

2022-07-06 12:38 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
>      @JoinColumn(name = "bakery_id")
오랜만에 봐서 기억이 가물가물 😭

2022-07-06 12:39 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
this.user 로 비교한 것이 최초등록자의 리뷰라서 그렇게 구현되어있습니다

2022-07-06 12:40 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
도영님이 필요하다하신부분이었던걸로 기억하는데 필요없다고 하시면 삭제하겠습니다

2022-07-06 12:43 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
좋은것같습니다!

2022-07-06 12:53 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +        return super.getExceptionResponse(request, messagePath, ex.getMessage());
```java
public Bakery findById(Long id) {
        return bakeryRepository.findById(id)
                .orElseThrow(() -> new BakeryNotFoundException(id));
    }
```
기존 Args 파라미터로 받는 부분은 응답시 메시지에 출력이 안되는걸로 테스트해서 message 필드로 변경해서 구현한것 같네요 
제가 잘못한것일 수도 있어서 확인 한번 부탁드립니다 🙏

2022-07-06 13:01 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +import com.bside.breadgood.ddd.bakery.application.exception.*;
아래 참고하여 옵션 변경하였습니다~~
[https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports](https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports)

2022-07-06 14:43 UTC, doyoungkim-29cm commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +                .findFirst()
맞습니다. 상관없긴한데 저는 습관적으로 findAny 사용합니다. 
해동님이 결정해주세요!

2022-07-06 14:45 UTC, doyoungkim-29cm commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/BakeryReview.java
>  public class BakeryReview extends BaseEntity {
롬북 기능중에 하나입니다! JPA 에서 가이드해주는 방식은 따로 있긴한데 아마 인텔리제이가 힌트 줄거에요!

2022-07-06 14:53 UTC, doyoungkim-29cm commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
BakeryWebViewController 로 옮겨 주시는 게 좋을 것 같아요

2022-07-06 15:01 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +        return super.getExceptionResponse(request, messagePath, ex.getMessage());
관련 테스트 코드가 있으면 쉽게 확인할 수 있을 것 같아요! 있으시면 공유 부탁드려욥!

2022-07-06 15:01 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/BakeryReview.java
>  public class BakeryReview extends BaseEntity {
롬북 기능중에 하나입니다! JPA 에서 가이드해주는 방식은 따로 있긴한데 아마 인텔리제이가 힌트 줄거에요!
https://blog.naver.com/PostView.naver?blogId=dktmrorl&logNo=222359154544&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView

2022-07-06 15:02 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +                .findFirst()
맞습니다. 상관없긴한데 저는 습관적으로 findAny 사용합니다.
해동님이 결정해주세요!

2022-07-06 15:02 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
BakeryWebViewController 로 옮겨 주시는 게 좋을 것 같아요

2022-07-06 15:02 UTC, doyoung0205 commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/domain/Bakery.java
> +    }
넵 최초 등록자의 첫번째 리뷰를 삭제 불가하다고 이해 하겠습니다!

2022-07-24 10:32 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryAdminController.java
> +    @DeleteMapping("/pages/webview-api/bakery/{bakeryId}/review/{reviewId}")
제가 URI를 잘못지정한것 같네요 🙇  
말씀하신 API는 등록되어있어서 해당 API URI를 수정하도록하겠습니다

2022-07-24 10:34 UTC, haedoang commented on breadgood-server/src/main/java/com/bside/breadgood/ddd/bakery/ui/BakeryControllerAdvice.java
> +        return super.getExceptionResponse(request, messagePath, ex.getMessage());
스웨거로 확인하였습니다

2022-07-24 10:49 UTC, merged